// Canonical fallback list of Consolve's 9 services.
// Strings copied verbatim from src/pages/Services.jsx (CATALOGUE) and
// src/components/ServiceCatalogue.jsx (SERVICES). Do not rewrite the copy here.
export const SERVICES_FALLBACK = [
  {
    service_id: "strategy",
    icon: "Target",
    name_en: "Strategy Consulting",
    name_ar: "الاستشارات الاستراتيجية",
    tagline_en: "We build strategies that drive growth and turn goals into actionable plans.",
    tagline_ar: "نبني استراتيجيات تدعم النمو وتحول الأهداف إلى خطط قابلة للتنفيذ.",
    goal_en: "Set the strategic direction, support growth, and strengthen the organization's competitive position.",
    goal_ar: "تحديد الاتجاه الاستراتيجي، ودعم النمو، وتعزيز المكانة التنافسية للكيان.",
    description_en: "We build strategies that help companies make clearer decisions and turn goals into actionable plans.",
    description_ar: "نبني استراتيجيات تساعد الشركات على اتخاذ قرارات أكثر وضوحًا وتحويل الأهداف إلى خطط قابلة للتنفيذ.",
    sub_services_en: [
      "Corporate strategy development",
      "Business unit strategy building",
      "Market entry and expansion strategies",
      "Strategic planning and execution roadmaps",
      "Market analysis and competitive benchmarking",
      "Vision, mission, and values formulation",
      "Digital transformation and innovation strategies",
      "Sustainability and responsibility strategies",
    ],
    sub_services_ar: [
      "تطوير الاستراتيجية المؤسسية",
      "بناء استراتيجيات وحدات الأعمال",
      "إعداد استراتيجيات دخول الأسواق والتوسع",
      "التخطيط الاستراتيجي وبناء خرائط التنفيذ",
      "التحليل السوقي والمقارنات التنافسية",
      "صياغة الرؤية والرسالة والقيم",
      "استراتيجيات التحول الرقمي والابتكار",
      "استراتيجيات الاستدامة والمسؤولية",
    ],
    display_order: 10,
    is_active: true,
  },
  {
    service_id: "management",
    icon: "Users",
    name_en: "Management Consulting",
    name_ar: "الاستشارات الإدارية",
    tagline_en: "Improve organizational effectiveness",
    tagline_ar: "رفع كفاءة المنظمة",
    goal_en: "Raise organizational efficiency, strengthen leadership alignment, and improve management effectiveness.",
    goal_ar: "رفع كفاءة المنظمة، وتعزيز مواءمة القيادة، وتحسين فاعلية الإدارة.",
    description_en: "",
    description_ar: "",
    sub_services_en: [
      "Organizational structure design and restructuring",
      "Performance management systems and KPIs",
      "Change and transformation management",
      "Leadership advisory and executive development",
      "Policy and procedure development",
      "Decision-making frameworks and methodologies",
    ],
    sub_services_ar: [
      "تصميم الهيكل التنظيمي وإعادة الهيكلة",
      "بناء أنظمة إدارة الأداء ومؤشرات القياس",
      "إدارة التغيير والتحول",
      "الاستشارات القيادية وتطوير التنفيذيين",
      "تطوير السياسات والإجراءات",
      "بناء أطر ومنهجيات اتخاذ القرار",
    ],
    display_order: 20,
    is_active: true,
  },
  {
    service_id: "grc",
    icon: "Scale",
    name_en: "Governance, Risk & Compliance",
    name_ar: "الحوكمة والمخاطر والامتثال",
    tagline_en: "Ensure compliance and risk control",
    tagline_ar: "ضمان الامتثال وتقليل المخاطر",
    goal_en: "Strengthen governance, control, and compliance, and reduce enterprise risks.",
    goal_ar: "تعزيز الحوكمة والرقابة والامتثال، وتقليل المخاطر المؤسسية.",
    description_en: "",
    description_ar: "",
    sub_services_en: [
      "Governance framework design",
      "Enterprise risk management and risk registers",
      "Internal audit and controls assessment",
      "Compliance program design",
      "Fraud risk management",
      "Business continuity and crisis management",
      "Sustainability and its reporting",
    ],
    sub_services_ar: [
      "تصميم أطر الحوكمة",
      "إدارة المخاطر المؤسسية وسجلات المخاطر",
      "التدقيق الداخلي وتقييم الضوابط",
      "تصميم برامج الامتثال",
      "إدارة مخاطر الاحتيال",
      "استمرارية الأعمال وإدارة الأزمات",
      "الاستدامة وإعداد تقاريرها",
    ],
    display_order: 30,
    is_active: true,
  },
  {
    service_id: "operations",
    icon: "Settings",
    name_en: "Operations Management Consulting",
    name_ar: "استشارات إدارة العمليات",
    tagline_en: "Optimize efficiency and cost",
    tagline_ar: "تحسين الكفاءة والتكاليف",
    goal_en: "Improve operational efficiency, raise productivity, and reduce waste and costs.",
    goal_ar: "تحسين الكفاءة التشغيلية، ورفع الإنتاجية، وتقليل الهدر والتكاليف.",
    description_en: "",
    description_ar: "",
    sub_services_en: [
      "Operating model design",
      "Process analysis and re-engineering",
      "Lean and Six Sigma implementation",
      "Supply chain optimization",
      "Procurement optimization",
      "Cost reduction programs",
      "Service delivery improvement",
      "Quality management systems",
    ],
    sub_services_ar: [
      "تصميم نموذج التشغيل",
      "تحليل العمليات وإعادة هندستها",
      "تطبيق منهجيات لين وسيجما",
      "تحسين سلاسل الإمداد",
      "تحسين المشتريات",
      "برامج خفض التكاليف",
      "تحسين تقديم الخدمات",
      "أنظمة إدارة الجودة",
    ],
    display_order: 40,
    is_active: true,
  },
  {
    service_id: "marketing",
    icon: "Megaphone",
    name_en: "Marketing Consulting",
    name_ar: "الاستشارات التسويقية",
    tagline_en: "Drive brand growth",
    tagline_ar: "تعزيز نمو العلامة",
    goal_en: "Support brand growth, strengthen customer acquisition, and improve market presence.",
    goal_ar: "دعم نمو العلامة التجارية، وتعزيز اكتساب العملاء، وتحسين الحضور السوقي.",
    description_en: "",
    description_ar: "",
    sub_services_en: [
      "Marketing strategy and plan development",
      "Brand building and positioning",
      "Digital marketing strategies",
      "Customer experience design",
      "Market research and customer analysis",
      "Pricing strategies",
      "Campaign management and performance optimization",
      "CRM strategies and implementation",
    ],
    sub_services_ar: [
      "إعداد استراتيجية وخطة التسويق",
      "بناء وتموضع العلامة التجارية",
      "استراتيجيات التسويق الرقمي",
      "تصميم تجربة العميل",
      "أبحاث السوق وتحليل العملاء",
      "استراتيجيات التسعير",
      "إدارة الحملات وتحسين الأداء",
      "استراتيجيات إدارة علاقات العملاء وتطبيقها",
    ],
    display_order: 50,
    is_active: true,
  },
  {
    service_id: "financial",
    icon: "DollarSign",
    name_en: "Financial Advisory",
    name_ar: "الاستشارات المالية",
    tagline_en: "Strengthen financial decisions",
    tagline_ar: "دعم القرارات المالية",
    goal_en: "Strengthen the financial position, support decision-making, and improve financial efficiency.",
    goal_ar: "تعزيز الوضع المالي، ودعم اتخاذ القرار، وتحسين الكفاءة المالية.",
    description_en: "",
    description_ar: "",
    sub_services_en: [
      "Financial planning and analysis",
      "Budgeting and forecasting",
      "Cost and profitability analysis",
      "Financial modeling and valuation",
      "Feasibility studies",
      "Capital structuring and fundraising",
      "Mergers and acquisitions advisory",
      "IPO readiness",
    ],
    sub_services_ar: [
      "التخطيط والتحليل المالي",
      "إعداد الميزانيات والتوقعات",
      "تحليل التكاليف والربحية",
      "النمذجة المالية والتقييم",
      "دراسات الجدوى",
      "هيكلة رأس المال وجذب التمويل",
      "الاستشارات في الاندماجات والاستحواذات",
      "التأهيل للطرح العام",
    ],
    display_order: 60,
    is_active: true,
  },
  {
    service_id: "legal",
    icon: "Gavel",
    name_en: "Legal Consulting",
    name_ar: "الاستشارات القانونية",
    tagline_en: "Ensure legal protection",
    tagline_ar: "حماية المصالح القانونية",
    goal_en: "Protect the company's interests, ensure legal compliance, and reduce regulatory risks.",
    goal_ar: "حماية مصالح الشركة، وضمان الامتثال القانوني، وتقليل المخاطر النظامية.",
    description_en: "",
    description_ar: "",
    sub_services_en: [
      "Company formation and structuring",
      "Contract drafting and review",
      "Regulatory and legislative compliance",
      "Legal governance frameworks",
      "Labor law advisory",
      "Dispute resolution support",
      "Intellectual property protection",
      "Commercial regulations advisory",
    ],
    sub_services_ar: [
      "تأسيس وهيكلة الشركات",
      "صياغة العقود ومراجعتها",
      "الامتثال للأنظمة والتشريعات",
      "الأطر القانونية للحوكمة",
      "استشارات نظام العمل",
      "دعم حل النزاعات",
      "حماية الملكية الفكرية",
      "الاستشارات في الأنظمة التجارية",
    ],
    display_order: 70,
    is_active: true,
  },
  {
    service_id: "bizdev",
    icon: "Rocket",
    name_en: "Business Development",
    name_ar: "تطوير الأعمال",
    tagline_en: "Unlock growth opportunities",
    tagline_ar: "فتح فرص النمو",
    goal_en: "Open growth opportunities, expand partnerships, and strengthen commercial expansion.",
    goal_ar: "فتح فرص النمو، وتوسيع الشراكات، وتعزيز التوسع التجاري.",
    description_en: "",
    description_ar: "",
    sub_services_en: [
      "Growth strategies and revenue models",
      "Partnership and alliance building",
      "Sales strategies and channel optimization",
      "Market entry strategies",
      "New venture launch support",
      "Customer acquisition strategies",
      "Commercial proposals and presentations",
    ],
    sub_services_ar: [
      "استراتيجيات النمو ونماذج الإيرادات",
      "بناء الشراكات والتحالفات",
      "استراتيجيات المبيعات وتحسين القنوات",
      "استراتيجيات دخول السوق",
      "دعم إطلاق المشاريع الجديدة",
      "استراتيجيات اكتساب العملاء",
      "إعداد العروض التجارية والتقديمية",
    ],
    display_order: 80,
    is_active: true,
  },
  {
    service_id: "rnd",
    icon: "Lightbulb",
    name_en: "R&D and Innovation",
    name_ar: "البحث والتطوير والابتكار",
    tagline_en: "Build future capabilities",
    tagline_ar: "بناء قدرات مستقبلية",
    goal_en: "Foster innovation, support solution development, and raise future readiness.",
    goal_ar: "تعزيز الابتكار، ودعم تطوير الحلول، ورفع الجاهزية للمستقبل.",
    description_en: "",
    description_ar: "",
    sub_services_en: [
      "Innovation strategies and frameworks",
      "Product development support",
      "R&D program design",
      "Technology scouting and assessment",
      "Design thinking workshops",
      "Launch-ready prototype development",
      "Digital transformation initiatives",
      "AI and data innovation",
    ],
    sub_services_ar: [
      "استراتيجيات الابتكار وأطره",
      "دعم تطوير المنتجات",
      "تصميم برامج البحث والتطوير",
      "استكشاف التقنيات وتقييمها",
      "ورش التفكير التصميمي",
      "تطوير النماذج الأولية القابلة للإطلاق",
      "مبادرات التحول الرقمي",
      "الابتكار في الذكاء الاصطناعي والبيانات",
    ],
    display_order: 90,
    is_active: true,
  },
];